version: 2
jobs:
  test:
    docker:
      - image: cimg/node:16.14.2
    steps:
      - checkout
      - run:
          command: yarn install
      - run:
          command: yarn test
      - run:
          command: yarn build
  release:
    docker:
      - image: cimg/node:16.14.2
    steps:
      - checkout
      - run:
          command: ./buildtask/release.sh
workflows:
  version: 2
  creasy-ui-pipeline:
    jobs:
      - test
      - hold:
          filters:
            branches:
              only: master
          type: approval
          requires:
            - test
      - release:
          filters:
            branches:
              only: master
          requires:
            - hold
